[DEBUG]
status = "Сервер B2X_FeedNews v.1.0"
admin = 'Super_user'

[USERS_TOKEN]
NN = 'Без авторизации'
0bc0df6d-83dc-44f0-8195-f19f679cdf7d = 'Super_user'
mng2 = 'Анатолий Филаткин'

# https://www.notion.so/Secrets-Management-730c82af2fc048d383d668c4049fb9bf

[DB]
db_name = 'data_feeds'
cust_namesrc = 'File'